# Generated by Django 3.2.25 on 2024-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240510_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Изображение опубликовано'),
        ),
    ]
